### ISSUE TITLE
AVIF detection is not working when a file is represented as an ArrayBuffer

### ISSUE THREAD

**Issue by prplx** [nir11/file-type-checker#13]
Hey, thanks for the great library! 

I found an issue when detecting avif files. When work with an ArrayBuffer, `isAvifStringIncluded` utility returns false for an avif file, hence `isAVIF` function also returns false.

`getFileChunk` preliminary converts ArrayBuffer into Uint8Array, in which numbers are stored in decimal format, therefore there is no need to parse them as hexadecimal here https://github.com/nir11/file-type-checker/blob/main/src/utils/index.ts#L158.

This implementation of the function would be sufficient:
```
export function isAvifStringIncluded(fileChunk: Array<number>): boolean {
  const signature = fileChunk
    .slice(4, 12)
    .map(hex => String.fromCharCode(hex))
    .join('')
  return signature === 'ftypavif'
}
```

**Comment by nir11** [comment]
Hey, great catch!
I’ve fixed it now.
Thanks!
